### ISSUE TITLE
What do you think is the future of APIs? 

### ISSUE THREAD

**Issue by CarlMungazi** [dashersw/ama#1]

**Comment by dashersw** [comment]
The current, _wonderful_ world of APIs are reminding me of the era when web services boomed. SOAP was developed as an effort to standardize service communication, and it failed arguably miserably due to their complexity.

A lot of entrepreneurs try to solve the challenge of combining various APIs in order to produce customizable workflows. I think this trend will continue, and might even improve with machine learning, but ultimately will stagnate as it still won't be able to solve the problem of customization of data between different APIs.

I think it's why products like [nodered](http://nodered.org) or [DoveCôte](https://dove-cote.co) are important for the future; little customizable blocks that interconnect various APIs. The company that invents an easy-to-reason-about, easy-to-learn custom DSL or a declarative syntax for this, will have the upper hand.
